### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by slucaskim** [tkpcchurch/ichthys#16]
- [x] 세례
- [ ] 가족 관계 - user requirement 필요함
- [x] 사진 업로드
- [x] 사용자 권한 (cancan)
- [ ] Phone number formatting

**Comment by hylee1201** [comment]
Google Map API을 이용해서 
- Map보여주기
- City, Province 이름을 autocomplete

**Comment by hylee1201** [comment]
DB information in herokku for data migration and creating its script
